const OPERATOR_CLICK = "OPERATOR_CLICK";
const NUM_CLICK = "NUM_CLICK";
const CALC_CLICK = "CALC_CLICK";
const CLEAR_CLICK = "CLEAR_CLICK";

export { OPERATOR_CLICK, NUM_CLICK, CALC_CLICK, CLEAR_CLICK };
