const OPERATOR_CLICK = "OPERATOR_CLICK";
const NUM_CLICK = "NUM_CLICK";
const CALC_CLICK = "CALC_CLICK";
const CLEAR_CLICK = "CLEAR_CLICK";
const POSITIVE_NEGATIVE_CLICK = "POSITIVE_NEGATIVE_CLICK";

export {
  OPERATOR_CLICK,
  NUM_CLICK,
  CALC_CLICK,
  CLEAR_CLICK,
  POSITIVE_NEGATIVE_CLICK
};
